# Generated by Django 5.1.2 on 2024-11-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount_Code', models.CharField(max_length=50)),
                ('Discount_Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Status', models.CharField(choices=[('THANH TOÁN THÀNH CÔNG', 'Thanh toán thành công'), ('THANH TOÁN KHÔNG THÀNH CÔNG', 'Thanh toán không thành công'), ('HOÀN TRẢ THÀNH CÔNG', 'Hoàn trả thành công')], max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method_Name', models.CharField(max_length=150)),
                ('Method_Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Expected_Date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('Tracking_Number', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('Shipment_Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Webtote.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('Order_Status', models.CharField(choices=[('ĐƠN HÀNG MỚI', 'Đơn hàng mới'), ('ĐÃ XÁC NHẬN ĐƠN HÀNG', 'Đã xác nhận'), ('ĐANG VẬN CHUYỂN', 'Đang vận chuyển'), ('GIAO THÀNH CÔNG', 'Giao thành công'), ('GIAO KHÔNG THÀNH CÔNG', 'Giao không thành công'), ('ĐÃ HỦY', 'Đã hủy'), ('HOÀN TRẢ', 'Hoàn trả'), ('TRẢ HÀNG THÀNH CÔNG', 'Trả hàng thành công')], max_length=50)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Reason', models.TextField(null=True)),
                ('Refund_Date', models.DateField(null=True)),
                ('Time_Refund_Money', models.DateTimeField(auto_now_add=True, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.customer')),
                ('Delivery_Infor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.deliveryinformation')),
                ('Discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.discount')),
                ('Payment_Method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.paymentmethod')),
                ('Payment_Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.paymentstatus')),
                ('Shipment_Method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.shipmentmethod')),
                ('Shipment_Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.shipmentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Date_Edited', models.DateField()),
                ('Date_Created', models.DateField()),
                ('Color', models.TextField()),
                ('Order', models.ManyToManyField(through='Webtote.OrderDetail', to='Webtote.order')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.product'),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.cart')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Primary', models.BooleanField()),
                ('Image_Url', models.URLField(max_length=50)),
                ('Alt_Text', models.TextField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtote.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Content', models.TextField()),
                ('Date_Created', models.DateField()),
                ('Date_Edited', models.DateTimeField(auto_now_add=True, null=True)),
                ('Order_Detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Webtote.orderdetail')),
            ],
        ),
    ]
