# Generated by Django 4.2.8 on 2024-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webtote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Unit_Price',
            field=models.IntegerField(),
        ),
    ]
