# Generated by Django 4.2.8 on 2024-11-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webtote', '0002_discount_is_active_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproduct',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.customer'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Discount_Value',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail', to='Webtote.order'),
        ),
        migrations.AlterField(
            model_name='shipmentstatus',
            name='Shipment_Status',
            field=models.CharField(choices=[('ĐANG VẬN CHUYỂN', 'Đang vận chuyển'), ('GIAO THÀNH CÔNG', 'Giao thành công'), ('GIAO KHÔNG THÀNH CÔNG', 'Giao không thành công'), ('ĐÃ HỦY', 'Đã hủy'), ('TRẢ HÀNG THÀNH CÔNG', 'Trả hàng thành công')], max_length=50),
        ),
    ]
