# Generated by Django 4.2.8 on 2024-12-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webtote', '0003_reviewproduct_customer_alter_discount_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='Cart',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='Cancel_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Return_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Return_Reason',
            field=models.CharField(blank=True, choices=[('missing_items', 'Nhận thiếu hàng'), ('damaged', 'Đơn hàng bị hư hỏng do vận chuyển'), ('no_longer_needed', 'Không còn nhu cầu sử dụng'), ('not_as_described', 'Sản phẩm khác với mô tả'), ('wrong_item', 'Sản phẩm nhận được không đúng')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_Method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Reason',
            field=models.CharField(blank=True, choices=[('update_address', 'Tôi muốn cập nhật địa chỉ/sđt giao hàng'), ('discount_code', 'Tôi muốn thêm/thay đổi mã giảm giá'), ('change_product', 'Tôi muốn thay đổi sản phẩm (màu sắc, số lượng,...)'), ('payment_issue', 'Thủ tục thanh toán rắc rối'), ('better_deal', 'Tôi tìm thấy chỗ mua khác tốt hơn (Rẻ hơn, giao nhanh hơn, uy tín hơn...)'), ('no_need', 'Tôi không có nhu cầu mua nữa')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Refund_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Shipment_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Webtote.shipmentstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='Payment_Status',
            field=models.CharField(blank=True, choices=[('THANH TOÁN THÀNH CÔNG', 'Thanh toán thành công'), ('THANH TOÁN KHÔNG THÀNH CÔNG', 'Thanh toán không thành công'), ('HOÀN TRẢ THÀNH CÔNG', 'Hoàn trả thành công')], max_length=70),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='Date_Edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
